name: Test libstatistics_collector
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test_macOS:
    runs-on: macOS-latest
    steps:
    - uses: ros-tooling/setup-ros@0.2.1
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: libstatistics_collector
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"]
            }
          }
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros_ws/log

  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.1
      with:
        package-name: libstatistics_collector
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        target-ros2-distro: foxy
    - uses: codecov/codecov-action@v2.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ros_ws/lcov/total_coverage.info
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: false
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: colcon-logs-${{ matrix.os }}
        path: ros_ws/log

  build_and_test_asan:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.1
      with:
        colcon-mixin-name: asan
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        package-name: libstatistics_collector
        target-ros2-distro: foxy
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: colcon-logs-ubuntu-asan
        path: ros_ws/log
